/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JButton;

/**
 *
 * @author neyda
 */
public class VistaAlumno extends javax.swing.JFrame {

    public VistaAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVistaAlu = new javax.swing.JPanel();
        jpTitulo = new javax.swing.JPanel();
        lbAlumno = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbNombre1 = new javax.swing.JLabel();
        lbApellido1 = new javax.swing.JLabel();
        lbDNI1 = new javax.swing.JLabel();
        lbDomicilio1 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfDNI = new javax.swing.JTextField();
        tfDomicilio = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollTablaAlu = new javax.swing.JScrollPane();
        jTableAlu = new javax.swing.JTable();
        jlFechaNac = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        dataChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        PanelVistaAlu.setBackground(new java.awt.Color(232, 255, 255));
        PanelVistaAlu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTitulo.setBackground(new java.awt.Color(204, 255, 255));

        lbAlumno.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lbAlumno.setForeground(new java.awt.Color(0, 0, 0));
        lbAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAlumno.setText("ALUMNO");
        lbAlumno.setToolTipText("");

        javax.swing.GroupLayout jpTituloLayout = new javax.swing.GroupLayout(jpTitulo);
        jpTitulo.setLayout(jpTituloLayout);
        jpTituloLayout.setHorizontalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpTituloLayout.setVerticalGroup(
            jpTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTituloLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelVistaAlu.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        lbTelefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(0, 0, 0));
        lbTelefono.setText("Domicilio");
        PanelVistaAlu.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 80, 20));

        lbNombre1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbNombre1.setForeground(new java.awt.Color(0, 0, 0));
        lbNombre1.setText("Nombre");
        PanelVistaAlu.add(lbNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, 40));

        lbApellido1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbApellido1.setForeground(new java.awt.Color(0, 0, 0));
        lbApellido1.setText("Apellido");
        PanelVistaAlu.add(lbApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 110, 40));

        lbDNI1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbDNI1.setForeground(new java.awt.Color(0, 0, 0));
        lbDNI1.setText("DNI");
        PanelVistaAlu.add(lbDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, -1));

        lbDomicilio1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbDomicilio1.setForeground(new java.awt.Color(0, 0, 0));
        lbDomicilio1.setText("Telefono");
        PanelVistaAlu.add(lbDomicilio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 80, -1));

        tfApellido.setBackground(new java.awt.Color(255, 255, 255));
        tfApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfApellido.setForeground(new java.awt.Color(153, 153, 153));
        tfApellido.setText("Apellido del alumno");
        tfApellido.setBorder(null);
        PanelVistaAlu.add(tfApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 220, 20));

        tfNombre.setBackground(new java.awt.Color(255, 255, 255));
        tfNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfNombre.setForeground(new java.awt.Color(153, 153, 153));
        tfNombre.setText("Nombre del alumno");
        tfNombre.setBorder(null);
        tfNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelVistaAlu.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 220, 20));

        tfTelefono.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfTelefono.setForeground(new java.awt.Color(153, 153, 153));
        tfTelefono.setText("Telefono del alumno");
        tfTelefono.setBorder(null);
        PanelVistaAlu.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 190, 20));

        tfDNI.setBackground(new java.awt.Color(255, 255, 255));
        tfDNI.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfDNI.setForeground(new java.awt.Color(153, 153, 153));
        tfDNI.setText("DNI sin puntos del alumno");
        tfDNI.setBorder(null);
        PanelVistaAlu.add(tfDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 190, 20));

        tfDomicilio.setBackground(new java.awt.Color(255, 255, 255));
        tfDomicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tfDomicilio.setForeground(new java.awt.Color(153, 153, 153));
        tfDomicilio.setText("Domicilio del alumno");
        tfDomicilio.setBorder(null);
        PanelVistaAlu.add(tfDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 190, 20));
        PanelVistaAlu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 220, 30));
        PanelVistaAlu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 220, 10));
        PanelVistaAlu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 190, 20));
        PanelVistaAlu.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 190, 10));
        PanelVistaAlu.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, -1, -1));
        PanelVistaAlu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 190, 20));

        jTableAlu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollTablaAlu.setViewportView(jTableAlu);

        PanelVistaAlu.add(jScrollTablaAlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 680, 170));

        jlFechaNac.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jlFechaNac.setForeground(new java.awt.Color(0, 0, 0));
        jlFechaNac.setText("Fecha de nacimiento");
        PanelVistaAlu.add(jlFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 190, 30));

        botonAgregar.setBackground(new java.awt.Color(0, 153, 153));
        botonAgregar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        botonAgregar.setText("Agregar");
        botonAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelVistaAlu.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 130, 40));

        botonModificar.setBackground(new java.awt.Color(0, 153, 153));
        botonModificar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonModificar.setForeground(new java.awt.Color(255, 255, 255));
        botonModificar.setText("Modificar");
        botonModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelVistaAlu.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 140, 40));

        botonEliminar.setBackground(new java.awt.Color(0, 153, 153));
        botonEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setText("Eliminar");
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelVistaAlu.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 150, 40));

        botonVolver.setBackground(new java.awt.Color(0, 153, 153));
        botonVolver.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelVistaAlu.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 620, 110, 40));
        PanelVistaAlu.add(dataChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 259, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVistaAlu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVistaAlu, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JDateChooser getDataChooser() {
        return dataChooser;
    }

    public void setDataChooser(JDateChooser dataChooser) {
        this.dataChooser = dataChooser;
    }

    public JButton getBotonAgregar() {
        return botonAgregar;
    }

    public void setBotonAgregar(JButton botonAgregar) {
        this.botonAgregar = botonAgregar;
    }

    public JButton getBotonEliminar() {
        return botonEliminar;
    }

    public void setBotonEliminar(JButton botonEliminar) {
        this.botonEliminar = botonEliminar;
    }

    public JButton getBotonModificar() {
        return botonModificar;
    }

    public void setBotonModificar(JButton botonModificar) {
        this.botonModificar = botonModificar;
    }

    public JButton getBotonVolver() {
        return botonVolver;
    }

    public void setBotonVolver(JButton botonVolver) {
        this.botonVolver = botonVolver;
    }

    public JScrollPane getjScrollTablaAlu() {
        return jScrollTablaAlu;
    }

    public void setjScrollTablaAlu(JScrollPane jScrollTablaAlu) {
        this.jScrollTablaAlu = jScrollTablaAlu;
    }

    public JTable getjTableAlu() {
        return jTableAlu;
    }

    public void setjTableAlu(JTable jTableAlu) {
        this.jTableAlu = jTableAlu;
    }

    public JTextField getTfApellido() {
        return tfApellido;
    }

    public void setTfApellido(JTextField tfApellido) {
        this.tfApellido = tfApellido;
    }

    public JTextField getTfDNI() {
        return tfDNI;
    }

    public void setTfDNI(JTextField tfDNI) {
        this.tfDNI = tfDNI;
    }

    public JTextField getTfDomicilio() {
        return tfDomicilio;
    }

    public void setTfDomicilio(JTextField tfDomicilio) {
        this.tfDomicilio = tfDomicilio;
    }

    public JTextField getTfNombre() {
        return tfNombre;
    }

    public void setTfNombre(JTextField tfNombre) {
        this.tfNombre = tfNombre;
    }

    public JTextField getTfTelefono() {
        return tfTelefono;
    }

    /**
     * @param args the command line arguments
     */
    public void setTfTelefono(JTextField tfTelefono) {
        this.tfTelefono = tfTelefono;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVistaAlu;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonVolver;
    private com.toedter.calendar.JDateChooser dataChooser;
    private javax.swing.JScrollPane jScrollTablaAlu;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTableAlu;
    private javax.swing.JLabel jlFechaNac;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JLabel lbAlumno;
    private javax.swing.JLabel lbApellido1;
    private javax.swing.JLabel lbDNI1;
    private javax.swing.JLabel lbDomicilio1;
    private javax.swing.JLabel lbNombre1;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfDomicilio;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
